# Generated by Django 4.2.27 on 2025-12-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "title_uz",
                    models.CharField(max_length=200, null=True, verbose_name="Title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, null=True, verbose_name="Title"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, null=True, verbose_name="Title"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=250, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Short Description"
                    ),
                ),
                (
                    "short_description_uz",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "short_description_en",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "short_description_ru",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_uz",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_ru",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="destinations/",
                        verbose_name="Main Image",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show on homepage",
                        verbose_name="Featured",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Meta Keywords"
                    ),
                ),
                (
                    "meta_keywords_uz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "meta_keywords_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "meta_keywords_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "meta_description_uz",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_description_en",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_description_ru",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="Meta Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destination",
                "verbose_name_plural": "Destinations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="destination_slug_528bb8_idx"),
                    models.Index(
                        fields=["published", "-created_at"],
                        name="destination_publish_c6fde9_idx",
                    ),
                ],
            },
        ),
    ]
