# Generated by Django 4.2.27 on 2025-12-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="average_cost",
            field=models.CharField(
                blank=True,
                help_text='e.g., "$500-$1000 per person"',
                max_length=200,
                verbose_name="Average Cost",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="average_cost_en",
            field=models.CharField(
                blank=True,
                help_text='e.g., "$500-$1000 per person"',
                max_length=200,
                null=True,
                verbose_name="Average Cost",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="average_cost_ru",
            field=models.CharField(
                blank=True,
                help_text='e.g., "$500-$1000 per person"',
                max_length=200,
                null=True,
                verbose_name="Average Cost",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="average_cost_uz",
            field=models.CharField(
                blank=True,
                help_text='e.g., "$500-$1000 per person"',
                max_length=200,
                null=True,
                verbose_name="Average Cost",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="best_time_to_visit",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Best Time to Visit"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="best_time_to_visit_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Best Time to Visit"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="best_time_to_visit_ru",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Best Time to Visit"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="best_time_to_visit_uz",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Best Time to Visit"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="destination",
            name="city_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="city_ru",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="city_uz",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="SEO title for search engines",
                max_length=200,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="meta_title_en",
            field=models.CharField(
                blank=True,
                help_text="SEO title for search engines",
                max_length=200,
                null=True,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="meta_title_ru",
            field=models.CharField(
                blank=True,
                help_text="SEO title for search engines",
                max_length=200,
                null=True,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="meta_title_uz",
            field=models.CharField(
                blank=True,
                help_text="SEO title for search engines",
                max_length=200,
                null=True,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="region",
            field=models.CharField(blank=True, max_length=100, verbose_name="Region"),
        ),
        migrations.AddField(
            model_name="destination",
            name="region_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Region"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="region_ru",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Region"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="region_uz",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Region"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="things_to_do",
            field=models.TextField(
                blank=True,
                help_text="List activities and attractions",
                verbose_name="Things to Do",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="things_to_do_en",
            field=models.TextField(
                blank=True,
                help_text="List activities and attractions",
                null=True,
                verbose_name="Things to Do",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="things_to_do_ru",
            field=models.TextField(
                blank=True,
                help_text="List activities and attractions",
                null=True,
                verbose_name="Things to Do",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="things_to_do_uz",
            field=models.TextField(
                blank=True,
                help_text="List activities and attractions",
                null=True,
                verbose_name="Things to Do",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="description",
            field=models.TextField(verbose_name="Full Description"),
        ),
        migrations.AlterField(
            model_name="destination",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Full Description"),
        ),
        migrations.AlterField(
            model_name="destination",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Full Description"),
        ),
        migrations.AlterField(
            model_name="destination",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Full Description"),
        ),
        migrations.AlterField(
            model_name="destination",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="destinations/",
                verbose_name="Cover Image",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="SEO description for search engines",
                max_length=160,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="meta_description_en",
            field=models.CharField(
                blank=True,
                help_text="SEO description for search engines",
                max_length=160,
                null=True,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="meta_description_ru",
            field=models.CharField(
                blank=True,
                help_text="SEO description for search engines",
                max_length=160,
                null=True,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="meta_description_uz",
            field=models.CharField(
                blank=True,
                help_text="SEO description for search engines",
                max_length=160,
                null=True,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated keywords",
                max_length=255,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="meta_keywords_en",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated keywords",
                max_length=255,
                null=True,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="meta_keywords_ru",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated keywords",
                max_length=255,
                null=True,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="meta_keywords_uz",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated keywords",
                max_length=255,
                null=True,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.CreateModel(
            name="DestinationGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="destinations/gallery/", verbose_name="Image"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption"
                    ),
                ),
                (
                    "caption_uz",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Caption"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Caption"
                    ),
                ),
                (
                    "caption_ru",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Caption"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order", verbose_name="Order"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="destinations.destination",
                        verbose_name="Destination",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
