# Generated by Django 4.2.27 on 2025-12-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="country",
            field=models.CharField(
                default="Unknown", max_length=100, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="country_en",
            field=models.CharField(
                default="Unknown", max_length=100, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="country_ru",
            field=models.CharField(
                default="Unknown", max_length=100, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="country_uz",
            field=models.CharField(
                default="Unknown", max_length=100, null=True, verbose_name="Country"
            ),
        ),
    ]
