# Generated by Django 4.2.27 on 2025-12-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0002_destination_country_destination_country_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="name",
            field=models.CharField(
                default="Destination", max_length=200, verbose_name="Destination Name"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="name_en",
            field=models.CharField(
                default="Destination",
                max_length=200,
                null=True,
                verbose_name="Destination Name",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="name_ru",
            field=models.CharField(
                default="Destination",
                max_length=200,
                null=True,
                verbose_name="Destination Name",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="name_uz",
            field=models.CharField(
                default="Destination",
                max_length=200,
                null=True,
                verbose_name="Destination Name",
            ),
        ),
    ]
