# Generated by Django 4.2.27 on 2025-12-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "destinations",
            "0002_destination_average_cost_destination_average_cost_en_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination",
            name="average_cost",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="average_cost_en",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="average_cost_ru",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="average_cost_uz",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="best_time_to_visit",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="best_time_to_visit_en",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="best_time_to_visit_ru",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="best_time_to_visit_uz",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="description",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="description_uz",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="things_to_do",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="things_to_do_en",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="things_to_do_ru",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="things_to_do_uz",
        ),
    ]
