# Generated by Django 4.2.27 on 2025-12-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0003_remove_destination_average_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="meta_description_en",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="meta_description_ru",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="meta_description_uz",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="meta_keywords_en",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="meta_keywords_ru",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="meta_keywords_uz",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="meta_title_en",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="meta_title_ru",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="meta_title_uz",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="region",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="region_en",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="region_ru",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="region_uz",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="short_description_en",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="short_description_ru",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="short_description_uz",
        ),
    ]
