# Generated by Django 4.2.27 on 2025-12-06 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("destinations", "0001_initial"),
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="gallery/", verbose_name="Image"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Caption"
                    ),
                ),
                (
                    "caption_uz",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Caption"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Caption"
                    ),
                ),
                (
                    "caption_ru",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Caption"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="destinations.destination",
                        verbose_name="Destination",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packages.package",
                        verbose_name="Package",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
                "ordering": ["order", "-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["destination", "order"],
                        name="gallery_gal_destina_6b6a0e_idx",
                    ),
                    models.Index(
                        fields=["package", "order"],
                        name="gallery_gal_package_96ae3c_idx",
                    ),
                ],
            },
        ),
    ]
