# Generated by Django 4.2.27 on 2025-12-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galleryimage",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
            },
        ),
        migrations.RemoveIndex(
            model_name="galleryimage",
            name="gallery_gal_destina_6b6a0e_idx",
        ),
        migrations.RemoveIndex(
            model_name="galleryimage",
            name="gallery_gal_package_96ae3c_idx",
        ),
        migrations.RemoveField(
            model_name="galleryimage",
            name="caption_en",
        ),
        migrations.RemoveField(
            model_name="galleryimage",
            name="caption_ru",
        ),
        migrations.RemoveField(
            model_name="galleryimage",
            name="caption_uz",
        ),
        migrations.RemoveField(
            model_name="galleryimage",
            name="order",
        ),
        migrations.AddIndex(
            model_name="galleryimage",
            index=models.Index(
                fields=["destination", "-uploaded_at"],
                name="gallery_gal_destina_e4eeed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="galleryimage",
            index=models.Index(
                fields=["package", "-uploaded_at"],
                name="gallery_gal_package_766d0a_idx",
            ),
        ),
    ]
