# Generated by Django 4.2.27 on 2025-12-07 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('itinerary', models.TextField(blank=True, help_text='Day-by-day itinerary', verbose_name='Itinerary')),
                ('itinerary_uz', models.TextField(blank=True, help_text='Day-by-day itinerary', null=True, verbose_name='Itinerary')),
                ('itinerary_en', models.TextField(blank=True, help_text='Day-by-day itinerary', null=True, verbose_name='Itinerary')),
                ('itinerary_ru', models.TextField(blank=True, help_text='Day-by-day itinerary', null=True, verbose_name='Itinerary')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('duration', models.CharField(help_text='e.g., "5 days 4 nights"', max_length=100, verbose_name='Duration')),
                ('duration_uz', models.CharField(help_text='e.g., "5 days 4 nights"', max_length=100, null=True, verbose_name='Duration')),
                ('duration_en', models.CharField(help_text='e.g., "5 days 4 nights"', max_length=100, null=True, verbose_name='Duration')),
                ('duration_ru', models.CharField(help_text='e.g., "5 days 4 nights"', max_length=100, null=True, verbose_name='Duration')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Duration (days)')),
                ('max_people', models.PositiveIntegerField(default=10, verbose_name='Max People')),
                ('inclusions', models.TextField(blank=True, help_text='What is included', verbose_name='Inclusions')),
                ('inclusions_uz', models.TextField(blank=True, help_text='What is included', null=True, verbose_name='Inclusions')),
                ('inclusions_en', models.TextField(blank=True, help_text='What is included', null=True, verbose_name='Inclusions')),
                ('inclusions_ru', models.TextField(blank=True, help_text='What is included', null=True, verbose_name='Inclusions')),
                ('exclusions', models.TextField(blank=True, help_text='What is not included', verbose_name='Exclusions')),
                ('exclusions_uz', models.TextField(blank=True, help_text='What is not included', null=True, verbose_name='Exclusions')),
                ('exclusions_en', models.TextField(blank=True, help_text='What is not included', null=True, verbose_name='Exclusions')),
                ('exclusions_ru', models.TextField(blank=True, help_text='What is not included', null=True, verbose_name='Exclusions')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='Main Image')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage', verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('meta_keywords_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('meta_keywords_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('meta_description_uz', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('meta_description_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('meta_description_ru', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='destinations.destination', verbose_name='Destination')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='packages_pa_slug_a25c8d_idx'), models.Index(fields=['published', 'available', '-created_at'], name='packages_pa_publish_c3a890_idx')],
            },
        ),
    ]
