# Generated by Django 4.2.27 on 2025-12-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_destination_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='featured',
        ),
    ]
