# Generated by Django 4.2.27 on 2025-12-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0003_remove_package_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="duration_days",
        ),
        migrations.RemoveField(
            model_name="package",
            name="exclusions",
        ),
        migrations.RemoveField(
            model_name="package",
            name="exclusions_en",
        ),
        migrations.RemoveField(
            model_name="package",
            name="exclusions_ru",
        ),
        migrations.RemoveField(
            model_name="package",
            name="exclusions_uz",
        ),
        migrations.RemoveField(
            model_name="package",
            name="inclusions",
        ),
        migrations.RemoveField(
            model_name="package",
            name="inclusions_en",
        ),
        migrations.RemoveField(
            model_name="package",
            name="inclusions_ru",
        ),
        migrations.RemoveField(
            model_name="package",
            name="inclusions_uz",
        ),
        migrations.RemoveField(
            model_name="package",
            name="itinerary",
        ),
        migrations.RemoveField(
            model_name="package",
            name="itinerary_en",
        ),
        migrations.RemoveField(
            model_name="package",
            name="itinerary_ru",
        ),
        migrations.RemoveField(
            model_name="package",
            name="itinerary_uz",
        ),
    ]
