# Generated by Django 4.2.27 on 2025-12-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Company Name")),
                ("logo", models.ImageField(upload_to="sponsors/", verbose_name="Logo")),
                (
                    "website_url",
                    models.URLField(blank=True, null=True, verbose_name="Website URL"),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Lower numbers appear first",
                        verbose_name="Display Order",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
