from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Destination(models.Model):
    """
    Destination model with multilingual support.
    Fields ending with _en, _uz, _ru will be auto-generated by modeltranslation.
    """
    # Base Information (will be translated by modeltranslation)
    name = models.CharField(_('Destination Name'), max_length=200, default='Destination')
    title = models.CharField(_('Title'), max_length=200)
    slug = models.SlugField(_('Slug'), max_length=250, unique=True, blank=True)

    # Location Information (will be translated by modeltranslation)
    country = models.CharField(_('Country'), max_length=100, default='Unknown')
    city = models.CharField(_('City'), max_length=100, blank=True)

    # Media
    main_image = models.ImageField(_('Cover Image'), upload_to='destinations/', blank=True, null=True)

    # Status and Metadata
    featured = models.BooleanField(_('Featured'), default=False, help_text=_('Show on homepage'))
    published = models.BooleanField(_('Published'), default=True)
    created_at = models.DateTimeField(_('Created At'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated At'), auto_now=True)

    class Meta:
        verbose_name = _('Destination')
        verbose_name_plural = _('Destinations')
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['slug']),
            models.Index(fields=['published', '-created_at']),
        ]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('destinations:destination_detail', kwargs={'slug': self.slug})


class DestinationGalleryImage(models.Model):
    """
    Gallery images for destinations.
    Multiple images can be added to each destination.
    """
    destination = models.ForeignKey(
        Destination,
        on_delete=models.CASCADE,
        related_name='gallery_images',
        verbose_name=_('Destination')
    )
    image = models.ImageField(_('Image'), upload_to='destinations/gallery/')
    caption = models.CharField(_('Caption'), max_length=200, blank=True)
    order = models.PositiveIntegerField(_('Order'), default=0, help_text=_('Display order'))
    created_at = models.DateTimeField(_('Created At'), auto_now_add=True)

    class Meta:
        verbose_name = _('Gallery Image')
        verbose_name_plural = _('Gallery Images')
        ordering = ['order', '-created_at']

    def __str__(self):
        return f"{self.destination.title} - Image {self.order}"

