from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Destination(models.Model):
    """
    Destination model with multilingual support.
    Fields ending with _en, _uz, _ru will be auto-generated by modeltranslation.
    """
    # Base fields (will be translated by modeltranslation)
    country = models.CharField(_('Country'), max_length=100, default='Unknown')
    name = models.CharField(_('Destination Name'), max_length=200, default='Destination')
    title = models.CharField(_('Title'), max_length=200)
    slug = models.SlugField(_('Slug'), max_length=250, unique=True, blank=True)
    short_description = models.CharField(_('Short Description'), max_length=500, blank=True)
    description = models.TextField(_('Description'))

    # Media
    main_image = models.ImageField(_('Main Image'), upload_to='destinations/', blank=True, null=True)

    # Metadata
    published = models.BooleanField(_('Published'), default=True)
    featured = models.BooleanField(_('Featured'), default=False, help_text=_('Show on homepage'))
    created_at = models.DateTimeField(_('Created At'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated At'), auto_now=True)

    # SEO
    meta_keywords = models.CharField(_('Meta Keywords'), max_length=255, blank=True)
    meta_description = models.CharField(_('Meta Description'), max_length=160, blank=True)

    class Meta:
        verbose_name = _('Destination')
        verbose_name_plural = _('Destinations')
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['slug']),
            models.Index(fields=['published', '-created_at']),
        ]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('destinations:destination_detail', kwargs={'slug': self.slug})

    @property
    def gallery_images(self):
        """Get all gallery images for this destination"""
        return self.galleryimage_set.all()
