# Generated by Django 4.2.27 on 2025-12-07 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('number_of_people', models.PositiveIntegerField(default=1, verbose_name='Number of People')),
                ('preferred_date', models.DateField(verbose_name='Preferred Travel Date')),
                ('message', models.TextField(blank=True, verbose_name='Message/Special Requests')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='packages.package', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='bookings_bo_status_eb4fb1_idx'), models.Index(fields=['email'], name='bookings_bo_email_2e2fb9_idx')],
            },
        ),
    ]
