from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Package(models.Model):
    """
    Tour Package model with multilingual support.
    Fields ending with _en, _uz, _ru will be auto-generated by modeltranslation.
    """
    # Base fields (will be translated by modeltranslation)
    title = models.CharField(_('Title'), max_length=200)
    slug = models.SlugField(_('Slug'), max_length=250, unique=True, blank=True)
    description = models.TextField(_('Description'))
    itinerary = models.TextField(_('Itinerary'), blank=True, help_text=_('Day-by-day itinerary'))

    # Pricing & Duration
    price = models.DecimalField(_('Price'), max_digits=10, decimal_places=2)
    currency = models.CharField(_('Currency'), max_length=3, default='USD')
    duration = models.CharField(_('Duration'), max_length=100, help_text=_('e.g., "5 days 4 nights"'))
    duration_days = models.PositiveIntegerField(_('Duration (days)'), default=1)

    # Capacity
    max_people = models.PositiveIntegerField(_('Max People'), default=10)

    # Inclusions/Exclusions (translatable)
    inclusions = models.TextField(_('Inclusions'), blank=True, help_text=_('What is included'))
    exclusions = models.TextField(_('Exclusions'), blank=True, help_text=_('What is not included'))

    # Media
    main_image = models.ImageField(_('Main Image'), upload_to='packages/', blank=True, null=True)

    # Availability
    available = models.BooleanField(_('Available'), default=True)
    published = models.BooleanField(_('Published'), default=True)
    featured = models.BooleanField(_('Featured'), default=False, help_text=_('Show on homepage'))

    # Metadata
    created_at = models.DateTimeField(_('Created At'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated At'), auto_now=True)

    # SEO
    meta_keywords = models.CharField(_('Meta Keywords'), max_length=255, blank=True)
    meta_description = models.CharField(_('Meta Description'), max_length=160, blank=True)

    class Meta:
        verbose_name = _('Package')
        verbose_name_plural = _('Packages')
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['slug']),
            models.Index(fields=['published', 'available', '-created_at']),
        ]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('packages:package_detail', kwargs={'slug': self.slug})

    @property
    def price_per_person(self):
        """Format price display"""
        return f"{self.currency} {self.price}"
